### ISSUE TITLE
pom.xml in video, not in github

### ISSUE THREAD

**Issue by autohandle** [AdamBien/aws-lambda-cdk-plain#2]
https://www.youtube.com/watch?v=rHq514-1aHM&t=27s

![github](https://user-images.githubusercontent.com/6686041/141370319-e28f1e96-bd58-45b5-8148-fccbb76c5094.jpg)

**Comment by AdamBien** [comment]
Thanks! I noticed that yesterday. The pom.xml was accidentally moved to the boundary package. See older commits.
